# Generated by Django 6.0.3 on 2026-04-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="response_text",
            field=models.CharField(default=None, max_length=16000),
            preserve_default=False,
        ),
    ]
